### ISSUE TITLE
docker images for assembler

### ISSUE THREAD

**Issue by kern3020** [BiocuriousDIYLab/CuttlefishWranglin#7]
Eric has requested  images for SOAP and spades

**Comment by Julian-Ramirez** [comment]
I haven't tried these Dockerfiles but, I do have these assemblers installed with conda

Here is the Docker pull commands for SOAP, Spades and SGA:
[**SOAP de novo**](https://bioconda.github.io/recipes/soapdenovo2/README.html)

docker pull quay.io/biocontainers/soapdenovo2

[**Spades**](https://bioconda.github.io/recipes/spades/README.html)

docker pull quay.io/biocontainers/spades

[**String Graph Assembler**](https://bioconda.github.io/recipes/sga/README.html)

docker pull quay.io/biocontainers/sga

**Comment by kern3020** [comment]
Strangely, I don't see Julian's comment. Sorry if this is a dup. 

```
I haven't tried these Dockerfiles but, I do have these assemblers installed with conda

Here is the Docker pull commands for SOAP, Spades and SGA:
SOAP de novo

docker pull quay.io/biocontainers/soapdenovo2

Spades

docker pull quay.io/biocontainers/spades

String Graph Assembler

docker pull quay.io/biocontainers/sga

```

**Comment by Julian-Ramirez** [comment]
Sorry I deleted my comment. I tried those pull commands and quay.io denied access. [I'm looking for a better alternative for containers right now](https://github.com/BioContainers/containers/blob/master/spades/3.6.0/Dockerfile).

**Comment by Julian-Ramirez** [comment]
I'm still a Docker newbie but, [I have found some containers that look promising](https://github.com/BioContainers/containers).

Are these the kind of Dockerfiles we are looking for?
SOAP, Spades and SGA:
[**SOAP de novo**](https://bioconda.github.io/recipes/soapdenovo2/README.html)

[SOAP de novo Dockerfile](https://github.com/BioContainers/containers/blob/master/soapdenovo/240/Dockerfile)

[**Spades**](https://bioconda.github.io/recipes/spades/README.html)

[spades Dockerfile](https://github.com/BioContainers/containers/blob/master/spades/3.6.0/Dockerfile)

[**String Graph Assembler**](https://bioconda.github.io/recipes/sga/README.html)

[sga Dockerfile](https://github.com/BioContainers/containers/blob/master/sga/0.10.13/Dockerfile)

**Comment by kern3020** [comment]
Yes @Julian-Ramirez, this looks promising. I foresee two usage conditions
1) launch a linux node with some cloud provider or an HPC at a university. It would be natural to use this directly. 
2) Using galaxy (or similar) platform. Happily they use conda. 
https://docs.galaxyproject.org/en/master/admin/conda_faq.html

**Comment by Julian-Ramirez** [comment]
@kern3020 Sweet thanks! I didn't know that galaxy can use conda packages, that will make it easier to get up and running.
