### ISSUE TITLE
Error Correction Phase suggestions

### ISSUE THREAD

**Issue by Julian-Ramirez** [BiocuriousDIYLab/CuttlefishWranglin#9]
Hello Everyone,

Error correction is crucial for assembly of genomes because, we don't want low quality sequences to interfere with our Eulerian walk through the graph. Does anyone have any suggestions on what program to use for the error correction phase of assembly (assuming we are using a De Bruijn Graph assembler)? I also wanted to know if error correction programs work universally for most assemblers.

![image](https://user-images.githubusercontent.com/32283999/35023356-218df582-faef-11e7-91e8-0b6f620d74d2.png)

Thank you
Julian Ramirez

**Comment by kern3020** [comment]
Along these lines  we may want to do is to trim the reads based on the Q scores. Eric and our Illumina instructors showed how Q scores go down after a certain point.  Also, the primers may calls some low scores at the beginning of the read. Fastqc should give us a good idea.

**Comment by kern3020** [comment]
Here is a relevant thread on the  ABySS group from 2015

abyss "best practices"?
https://groups.google.com/forum/#!topic/abyss-users/uAX9MwJMTcc
